[directory]
style = "bold dimmed fg:#023047"
truncation_length = 3
truncate_to_repo = true

[character]
success_symbol = "[âœ](bold #219ebc)"
error_symbol = "[âœ](bold #fb8500)"

[nodejs]
format = "[$symbol($version)]($style) "
style = "bold dimmed fg:#219ebc"

[rust]
format = "[$symbol($version)]($style) "
style = "bold dimmed fg:#fb8500"

[package]
format = "[$symbol$version]($style) "
style = "#ffb703 dimmed bold"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold underline #FFB703"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold  green"
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[+$count](#219ebc)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[cmd_duration]
format = "took [$duration]($style) "
style = "#ffb703 bold"
min_time = 2000

[time]
disabled = false
format = "[$time]($style) "
style = "#8ecae6"
time_format = "%H:%M"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡"
discharging_symbol = "ğŸ’€"

[[battery.display]]
threshold = 15
style = "bold #fb8500"

[[battery.display]]
threshold = 50
style = "bold #ffb703"

[gcloud]
format = "[$domain]($style) "
style = "dimmed #8ECAE6"
